apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xojg716s7-java-quarkus-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/xojg716s7-java-quarkus